# Generated by Django 3.1.7 on 2021-04-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_saved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search', to='movies.movie')),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favoris', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
