# Generated by Django 3.1.7 on 2021-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_released', models.CharField(max_length=50)),
                ('run_time', models.CharField(max_length=50)),
                ('image_movie', models.URLField(max_length=255)),
                ('plot', models.TextField()),
                ('actor', models.ManyToManyField(related_name='movie', to='movies.Actor')),
                ('category', models.ManyToManyField(related_name='movies', to='movies.Category')),
            ],
        ),
    ]
