# Generated by Django 3.1.7 on 2021-03-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movie', to='movies.Actor'),
        ),
    ]
